name: catheter-CycleGAN
channels:
- pytorch
- defaults
dependencies:
- python=3.6
- pytorch=1.4.0
- scipy
- pip
- pip:
  - dominate==2.4.0
  - torchvision==0.5.0
  - Pillow==6.1.0
  - numpy==1.16.4
  - visdom==0.1.8
  - wandb==0.12.7
  - barbar==0.2.1
  - scikit-image==0.17.2
  - opencv-python==4.5.4.60