# python train_cycle_unet.py --name cyclegan_cldice_unet_testrun --model cycle_gan_cldice_unet --gpu_ids 4,5,6,7  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 4  --no_flip --save_epoch_freq 1 --epoch_count 1 --n_epochs 1 --n_epochs_decay 0 --load_size 512 --crop_size 512  --train_phase 1 --load_unet '/home/viktor/catheter-CycleGAN/catheter-CycleGAN/2022-11-2420-02-23/best_metric_model_ep20_0-983.pth' --lambda_2 0
# lambda 0.1
# python train_cycle_unet.py --name cyclegan_cldice_unet_30ep_lambda_1 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 0  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 2 --no_flip --save_epoch_freq 1 --epoch 50 --continue_train --epoch_count 51 --n_epochs 70 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/catheter-CycleGAN/2022-11-2420-02-23/best_metric_model_ep20_0-983.pth' --lambda_2 0.1
# lambda 0.3
# python train_cycle_unet.py --name cyclegan_cldice_unet_30ep_lambda_3 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 0  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 2 --no_flip --save_epoch_freq 1 --epoch 50 --continue_train --epoch_count 51 --n_epochs 70 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/catheter-CycleGAN/2022-11-2420-02-23/best_metric_model_ep20_0-983.pth' --lambda_2 0.3
# lambda 0.5
# python train_cycle_unet.py --name cyclegan_cldice_unet_30ep_lambda_5 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 0  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 2 --no_flip --save_epoch_freq 5 --epoch 70 --continue_train --epoch_count 81 --n_epochs 65 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/catheter-CycleGAN/2022-11-2420-02-23/best_metric_model_ep20_0-983.pth' --lambda_2 0.5
# lambda 0.7
# python train_cycle_unet.py --name cyclegan_cldice_unet_30ep_lambda_7 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 0  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 2 --no_flip --save_epoch_freq 5 --epoch 70 --continue_train --epoch_count 71 --n_epochs 65 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/catheter-CycleGAN/2022-11-2420-02-23/best_metric_model_ep20_0-983.pth' --lambda_2 0.7
# lambda 0
# python train_cycle_unet.py --name cyclegan_cldice_unet_30ep_lambda_0 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 0  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 2 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 65 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/catheter-CycleGAN/2022-11-2420-02-23/best_metric_model_ep20_0-983.pth' --lambda_2 0

# test run 25iter 0.1 (16,32,64,128,256) unet cldice
# python train_cycle_unet.py --name cyclegan_cldice_unet_testrun --model cycle_gan_cldice_unet --gpu_ids 1  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 1  --no_flip --save_epoch_freq 1 --epoch_count 1 --n_epochs 1 --n_epochs_decay 0 --load_size 512 --crop_size 512  --train_phase 1 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2620-05-06/best_metric_model_ep14_0-982.pth' --lambda_2 0
# use larger unet
# lambda 0.1
#python train_cycle_unet.py --name cycle30ep_cl_unet_large_lambda_1 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 1  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 2 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 65 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_larger/best_metric_model_ep32_0-985.pth' --lambda_2 0.1
# lambda 0.3
# python train_cycle_unet.py --name cycle30ep_cl_unet_large_lambda_3 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 4,5  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 2 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 15 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_larger/best_metric_model_ep32_0-985.pth' --lambda_2 0.3
# lambda 0.5
# test pretran 是否有效
# python train_cycle_unet.py --name cycle30ep_cl_unet_large_lambda_5 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 4,5  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 2 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 65 --n_epochs_decay 25 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_larger/best_metric_model_ep32_0-985.pth' --lambda_2 0.5
# python train_cycle_unet.py --name cycle30ep_cl_unet_pretran_large_lambda_5 --use_wandb --model cycle_gan_cldice_pretran_unet --gpu_ids 1,2  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 2 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_larger/best_metric_model_ep32_0-985.pth' --lambda_2 0.5
# pretran无效 不要用了


# 尝试其他的cldice unet
# python train_cycle_unet.py --name cyclegan_cldice_25_1_lambda_1 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 1,2  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 4 --no_flip --save_epoch_freq 5 --epoch 60 --continue_train --epoch_count 61 --n_epochs 60 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2620-05-06/best_metric_model_ep14_0-982.pth' --lambda_2 0.1
# python train_cycle_unet.py --name cyclegan_cldice_25_1_lambda_3 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 1,2  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 4 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2620-05-06/best_metric_model_ep14_0-982.pth' --lambda_2 0.3
# python train_cycle_unet.py --name cyclegan_cldice_25_1_lambda_5 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 1,2  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 4 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2620-05-06/best_metric_model_ep14_0-982.pth' --lambda_2 0.5
# python train_cycle_unet.py --name cyclegan_cldice_25_1_lambda_7 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 1,2  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 4 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2620-05-06/best_metric_model_ep14_0-982.pth' --lambda_2 0.7
# python train_cycle_unet.py --name cyclegan_cldice_25_1_lambda_0 --model cycle_gan_cldice_unet --gpu_ids 0,1  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 4 --no_flip --save_epoch_freq 5 --epoch 65 --continue_train --epoch_count 66 --n_epochs 60 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2620-05-06/best_metric_model_ep14_0-982.pth' --lambda_2 0

#尝试 25iter的其他lambda
# test run
# python train_cycle_unet.py --name cyclegan_cldice_unet_testrun_4 --model cycle_gan_cldice_unet --gpu_ids 2,4  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 2  --no_flip --save_epoch_freq 1 --epoch_count 1 --n_epochs 1 --n_epochs_decay 0 --load_size 512 --crop_size 512  --train_phase 1 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2514-43-59/best_metric_model_ep7_0-98.pth' --lambda_2 0
# python train_cycle_unet.py --name cyclegan_cldice_unet_testrun_3 --model cycle_gan_cldice_unet --gpu_ids 2,4  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 2  --no_flip --save_epoch_freq 1 --epoch_count 1 --n_epochs 1 --n_epochs_decay 0 --load_size 512 --crop_size 512  --train_phase 1 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2612-06-31/best_metric_model_ep19_0-984.pth' --lambda_2 0
# python train_cycle_unet.py --name cyclegan_cldice_unet_testrun_2 --model cycle_gan_cldice_unet --gpu_ids 2,4  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 2  --no_flip --save_epoch_freq 1 --epoch_count 1 --n_epochs 1 --n_epochs_decay 0 --load_size 512 --crop_size 512  --train_phase 1 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2613-44-29/best_metric_model_ep18_0-984.pth' --lambda_2 0

# 25 0.4
# python train_cycle_unet.py --name cyclegan_cldice_25_4_lambda_1 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 2,4  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 4 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2514-43-59/best_metric_model_ep7_0-98.pth' --lambda_2 0.1
# python train_cycle_unet.py --name cyclegan_cldice_25_4_lambda_3 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 2,4  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 4 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2514-43-59/best_metric_model_ep7_0-98.pth' --lambda_2 0.3
# python train_cycle_unet.py --name cyclegan_cldice_25_4_lambda_5 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 2,4  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 4 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2514-43-59/best_metric_model_ep7_0-98.pth' --lambda_2 0.5
# python train_cycle_unet.py --name cyclegan_cldice_25_4_lambda_7 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 2,4  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 4 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2514-43-59/best_metric_model_ep7_0-98.pth' --lambda_2 0.7
# python train_cycle_unet.py --name cyclegan_cldice_25_4_lambda_0 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 2,4  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 4 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2514-43-59/best_metric_model_ep7_0-98.pth' --lambda_2 0

# 25 0.3
# python train_cycle_unet.py --name cyclegan_cldice_25_3_lambda_1 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 2,4  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 4 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2612-06-31/best_metric_model_ep19_0-984.pth' --lambda_2 0.1
# python train_cycle_unet.py --name cyclegan_cldice_25_3_lambda_3 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 2,4  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 4 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2612-06-31/best_metric_model_ep19_0-984.pth' --lambda_2 0.3
# python train_cycle_unet.py --name cyclegan_cldice_25_3_lambda_5 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 2,4  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 4 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2612-06-31/best_metric_model_ep19_0-984.pth' --lambda_2 0.5
# python train_cycle_unet.py --name cyclegan_cldice_25_3_lambda_7 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 2,4  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 4 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2612-06-31/best_metric_model_ep19_0-984.pth' --lambda_2 0.7
# python train_cycle_unet.py --name cyclegan_cldice_25_3_lambda_0 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 2,4  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 4 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2612-06-31/best_metric_model_ep19_0-984.pth' --lambda_2 0


# 25 0.2
# python train_cycle_unet.py --name cyclegan_cldice_25_2_lambda_1 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 2,4  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 4 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2613-44-29/best_metric_model_ep18_0-984.pth' --lambda_2 0.1
# python train_cycle_unet.py --name cyclegan_cldice_25_2_lambda_3 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 2,4  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 4 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2613-44-29/best_metric_model_ep18_0-984.pth' --lambda_2 0.3
# python train_cycle_unet.py --name cyclegan_cldice_25_2_lambda_5 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 2,4  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 4 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2613-44-29/best_metric_model_ep18_0-984.pth' --lambda_2 0.5
# python train_cycle_unet.py --name cyclegan_cldice_25_2_lambda_7 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 2,4  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 4 --no_flip --save_epoch_freq 5 --epoch 50 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 20 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2613-44-29/best_metric_model_ep18_0-984.pth' --lambda_2 0.7
python train_cycle_unet.py --name cyclegan_cldice_25_2_lambda_0 --use_wandb --model cycle_gan_cldice_unet --gpu_ids 4,5  --checkpoints_dir './checkpoints_cyclegan_cldice' --batch_size 4 --no_flip --save_epoch_freq 5 --epoch 60 --continue_train --epoch_count 61 --n_epochs 60 --n_epochs_decay 15 --load_size 512 --crop_size 512  --train_phase 2 --load_unet '/home/viktor/catheter-CycleGAN/basic_clunet_models/2022-11-2613-44-29/best_metric_model_ep18_0-984.pth' --lambda_2 0