# python train_cycle_unet.py --name cyclegan_50ep --use_wandb --model cycle_gan_unet --gpu_ids 1  --batch_size 1 --preprocess none --no_flip --epoch 60 --continue_train --epoch_count 61 --n_epochs 60 --n_epochs_decay 10 --load_size 512 --crop_size 512  --train_phase 2 --lambda_2 0.5
# python train_cycle_unet.py --name cycle_unet --use_wandb --model cycle_gan_unet --gpu_ids 0 --batch_size 2 --n_epochs 80 --n_epochs_decay 40 --load_size 512 --crop_size 512
# python train_cycle_unet.py --name cycle_unet_parallel --use_wandb --model cycle_gan_unet --gpu_ids 1,2,3,4  --batch_size 4 --epoch 48 --continue_train --epoch_count 49 --n_epochs 80 --n_epochs_decay 40 --load_size 512 --crop_size 512  --train_phase 2
# python train_cycle_unet.py --name cycle_unet --use_wandb --model cycle_gan_unet --gpu_ids 5,6  --batch_size 4 --epoch 80 --continue_train --epoch_count 81 --n_epochs 80 --n_epochs_decay 40 --load_size 512 --crop_size 512  --train_phase 3 --lambda_2 0.1
# 50_10_20_10
# python train_cycle_unet.py --name cycle_unet_check --use_wandb --model cycle_gan_unet --gpu_ids 1,2,3,4  --batch_size 4 --preprocess none --no_flip --epoch 65 --continue_train --epoch_count 66 --n_epochs 60 --n_epochs_decay 30 --load_size 512 --crop_size 512  --train_phase 2 --lambda_2 0.1
# 50_10_10_5
# python train_cycle_unet.py --name u_net_5ep --use_wandb --model cycle_gan_unet --gpu_ids 5  --batch_size 1 --preprocess none --no_flip --epoch 70 --save_epoch_freq 1 --continue_train --epoch_count 71 --n_epochs 60 --n_epochs_decay 15 --load_size 512 --crop_size 512  --train_phase 4 --lambda_2 0.1
# experiment lambda_seg = 0
# python train_cycle_unet.py --name cyclegan_50ep_lambda_0 --use_wandb --model cycle_gan_unet --gpu_ids 0,1,2,3  --batch_size 4 --preprocess none --no_flip --epoch 50 --save_epoch_freq 1 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 15 --load_size 512 --crop_size 512  --train_phase 2 --lambda_2 0
# experiment lambda_seg = 0.3
# python train_cycle_unet.py --name cyclegan_50ep_lambda_0_3 --use_wandb --model cycle_gan_unet --gpu_ids 0,1,2,3  --batch_size 4 --preprocess none --no_flip --epoch 50 --save_epoch_freq 1 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 15 --load_size 512 --crop_size 512  --train_phase 2 --lambda_2 0.3
# experiment lambda_seg = 0.5
# python train_cycle_unet.py --name cyclegan_50ep_lambda_0_5 --use_wandb --model cycle_gan_unet --gpu_ids 0,1,2,3  --batch_size 4 --preprocess none --no_flip --epoch 50 --save_epoch_freq 1 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 15 --load_size 512 --crop_size 512  --train_phase 2 --lambda_2 0.5
# 用新的unet进行训练
# lambda 0.1
# python train_cycle_unet.py --name cycle_new_unet_lambda_1 --use_wandb --model cycle_gan_unet --gpu_ids 0,1,2,3  --batch_size 4 --preprocess none --no_flip --epoch 50 --save_epoch_freq 1 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 15 --load_size 512 --crop_size 512  --train_phase 2 --lambda_2 0.1 --load_unet '/home/viktor/catheter-CycleGAN/basic_unet_models/2022-11-2319-09-23/best_metric_model_ep6_0-92.pth'
# lambda 0.3
# python train_cycle_unet.py --name cycle_new_unet_lambda_3 --use_wandb --model cycle_gan_unet --gpu_ids 0,1,2,3  --batch_size 4 --preprocess none --no_flip --epoch 50 --save_epoch_freq 1 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 15 --load_size 512 --crop_size 512  --train_phase 2 --lambda_2 0.3 --load_unet '/home/viktor/catheter-CycleGAN/basic_unet_models/2022-11-2319-09-23/best_metric_model_ep6_0-92.pth'
# lambda 0
# python train_cycle_unet.py --name cycle_new_unet_lambda_0 --use_wandb --model cycle_gan_unet --gpu_ids 4,5,6,7  --batch_size 4 --preprocess none --no_flip --epoch 50 --save_epoch_freq 1 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 15 --load_size 512 --crop_size 512  --train_phase 2 --lambda_2 0 --load_unet '/home/viktor/catheter-CycleGAN/basic_unet_models/2022-11-2319-09-23/best_metric_model_ep6_0-92.pth'
# lambda 0.5
# python train_cycle_unet.py --name cycle_new_unet_lambda_5 --use_wandb --model cycle_gan_unet --gpu_ids 0,1,2,3  --batch_size 4 --preprocess none --no_flip --epoch 50 --save_epoch_freq 1 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 15 --load_size 512 --crop_size 512  --train_phase 2 --lambda_2 0.5 --load_unet '/home/viktor/catheter-CycleGAN/basic_unet_models/2022-11-2319-09-23/best_metric_model_ep6_0-92.pth'
# lambda 0.7
# python train_cycle_unet.py --name cycle_new_unet_lambda_7 --use_wandb --model cycle_gan_unet --gpu_ids 0,1,2,3  --batch_size 4 --preprocess none --no_flip --epoch 50 --save_epoch_freq 1 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 15 --load_size 512 --crop_size 512  --train_phase 2 --lambda_2 0.7 --load_unet '/home/viktor/catheter-CycleGAN/basic_unet_models/2022-11-2319-09-23/best_metric_model_ep6_0-92.pth'
# 重新训练一个cycleGAN
# python train_cycle_unet.py --name basic_cyclegan --checkpoints_dir './checkpoints_new_basic_cyclegan' --use_wandb --model cycle_gan_unet --gpu_ids 0,1,2,3  --batch_size 4 --preprocess none --no_flip --save_epoch_freq 1  --epoch_count 1 --n_epochs 50 --n_epochs_decay 0 --load_size 512 --crop_size 512  --train_phase 1 --lambda_2 0 --load_unet '/home/viktor/catheter-CycleGAN/basic_unet_models/2022-11-2319-09-23/best_metric_model_ep6_0-92.pth'
# python train_cycle_unet.py --name basic_cyclegan_no_normalize --checkpoints_dir './checkpoints_new_basic_cyclegan' --use_wandb --model cycle_gan_unet --gpu_ids 0,1,2,3  --batch_size 4 --no_flip --save_epoch_freq 5  --epoch_count 1 --n_epochs 50 --n_epochs_decay 0 --load_size 512 --crop_size 512  --train_phase 1 --lambda_2 0 --load_unet '/home/viktor/catheter-CycleGAN/basic_unet_models/2022-11-2319-09-23/best_metric_model_ep6_0-92.pth'
# python train_cycle_unet.py --name basic_cyclegan_no_normalize_recrop --checkpoints_dir './checkpoints_new_basic_cyclegan' --use_wandb --model cycle_gan_unet --gpu_ids 0  --batch_size 2 --no_flip --save_epoch_freq 5  --epoch_count 1 --n_epochs 15 --n_epochs_decay 35 --load_size 512 --crop_size 512  --train_phase 1 --lambda_2 0 --load_unet '/home/viktor/catheter-CycleGAN/basic_unet_models/2022-11-2319-09-23/best_metric_model_ep6_0-92.pth'

# 用重新训练的cyclegan 30ep试一下lambda = 0.1 0.3
# python train_cycle_unet.py --name cycle_new_unet_30ep_lambda_5 --use_wandb --model cycle_gan_unet --gpu_ids 0,1,2,3  --batch_size 4  --no_flip --epoch 50 --save_epoch_freq 1 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 15 --load_size 512 --crop_size 512  --train_phase 2 --lambda_2 0.5 --load_unet '/home/viktor/catheter-CycleGAN/basic_unet_models/2022-11-2319-09-23/best_metric_model_ep6_0-92.pth'
 python train_cycle_unet.py --name cycle_new_unet_30ep_lambda_3 --use_wandb --model cycle_gan_unet --gpu_ids 2,4  --batch_size 2  --no_flip --epoch 50 --save_epoch_freq 5 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 15 --load_size 512 --crop_size 512  --train_phase 2 --lambda_2 0.3 --load_unet '/home/viktor/catheter-CycleGAN/basic_unet_models/2022-11-2319-09-23/best_metric_model_ep6_0-92.pth'
# lambda 3 要重新跑 crash了
# python train_cycle_unet.py --name cycle_new_unet_30ep_lambda_7 --use_wandb --model cycle_gan_unet --gpu_ids 0,1,2,3  --batch_size 4  --no_flip --epoch 50 --save_epoch_freq 1 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 15 --load_size 512 --crop_size 512  --train_phase 2 --lambda_2 0.7 --load_unet '/home/viktor/catheter-CycleGAN/basic_unet_models/2022-11-2319-09-23/best_metric_model_ep6_0-92.pth'
# python train_cycle_unet.py --name cycle_new_unet_30ep_lambda_1 --use_wandb --model cycle_gan_unet --gpu_ids 0,1,2,3  --batch_size 4  --no_flip --epoch 50 --save_epoch_freq 1 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 15 --load_size 512 --crop_size 512  --train_phase 2 --lambda_2 0.1 --load_unet '/home/viktor/catheter-CycleGAN/basic_unet_models/2022-11-2319-09-23/best_metric_model_ep6_0-92.pth'
# python train_cycle_unet.py --name cycle_new_unet_30ep_lambda_0 --use_wandb --model cycle_gan_unet --gpu_ids 2,4 --batch_size 2  --no_flip --epoch 50 --save_epoch_freq 5 --continue_train --epoch_count 51 --n_epochs 60 --n_epochs_decay 15 --load_size 512 --crop_size 512  --train_phase 2 --lambda_2 0 --load_unet '/home/viktor/catheter-CycleGAN/basic_unet_models/2022-11-2319-09-23/best_metric_model_ep6_0-92.pth'
